-- HostForge migration: new tables from Kenneth Abejuela sync (2026-09-19)
-- Target: unified HostForge MariaDB (sms2_db / hf_db_*) which uses sms_ / crad_ prefixes
-- Safe to re-run (IF NOT EXISTS)

CREATE TABLE IF NOT EXISTS `sms_admin_announcements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(180) NOT NULL,
  `body` TEXT NOT NULL,
  `image_path` VARCHAR(255) NULL,
  `status` ENUM('published','unpublished') NOT NULL DEFAULT 'published',
  `audience` VARCHAR(40) NOT NULL DEFAULT 'student',
  `created_by` INT UNSIGNED NULL,
  `created_by_name` VARCHAR(150) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `published_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ann_status_published` (`status`, `published_at`),
  KEY `idx_ann_audience` (`audience`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sms_student_profiles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `student_id` VARCHAR(40) NOT NULL,
  `program` VARCHAR(200) NOT NULL DEFAULT 'Bachelor of Science in Information Technology',
  `year_level` VARCHAR(40) NOT NULL DEFAULT '4th Year',
  `section` VARCHAR(40) NOT NULL DEFAULT 'BSIT 4A',
  `semester` VARCHAR(40) NOT NULL DEFAULT '1st Semester',
  `school_year` VARCHAR(20) NOT NULL DEFAULT '2026-2027',
  `enrollment_status` VARCHAR(40) NOT NULL DEFAULT 'Enrolled',
  `standing` VARCHAR(40) NOT NULL DEFAULT 'Good Standing',
  `mobile` VARCHAR(40) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  `guardian` VARCHAR(150) DEFAULT NULL,
  `guardian_contact` VARCHAR(40) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sp_user` (`user_id`),
  UNIQUE KEY `uq_sp_student_id` (`student_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `crad_research_services_clearances` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `research_group_id` INT UNSIGNED NOT NULL,
  `research_stage` VARCHAR(20) NOT NULL DEFAULT 'research_1',
  `title_approval_id` INT UNSIGNED DEFAULT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'draft',
  `or_number` VARCHAR(80) NOT NULL DEFAULT '',
  `leader_student_no` VARCHAR(40) NOT NULL DEFAULT '',
  `leader_group_no` VARCHAR(40) NOT NULL DEFAULT '',
  `program` VARCHAR(200) NOT NULL DEFAULT '',
  `section` VARCHAR(80) NOT NULL DEFAULT '',
  `research_title` VARCHAR(255) NOT NULL DEFAULT '',
  `members_json` LONGTEXT DEFAULT NULL,
  `grammarian_name` VARCHAR(160) NOT NULL DEFAULT '',
  `statistician_name` VARCHAR(160) NOT NULL DEFAULT '',
  `adviser_name` VARCHAR(160) NOT NULL DEFAULT '',
  `adviser_user_id` INT UNSIGNED DEFAULT NULL,
  `adviser_email` VARCHAR(190) NOT NULL DEFAULT '',
  `adviser_signature` LONGTEXT DEFAULT NULL,
  `adviser_signed_at` DATETIME DEFAULT NULL,
  `crad_name` VARCHAR(160) NOT NULL DEFAULT '',
  `crad_user_id` INT UNSIGNED DEFAULT NULL,
  `crad_signature` LONGTEXT DEFAULT NULL,
  `crad_signed_at` DATETIME DEFAULT NULL,
  `uploaded_file` VARCHAR(255) DEFAULT NULL,
  `uploaded_original` VARCHAR(255) DEFAULT NULL,
  `uploaded_at` DATETIME DEFAULT NULL,
  `mis_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `aa_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `mis_verified_at` DATETIME DEFAULT NULL,
  `aa_verified_at` DATETIME DEFAULT NULL,
  `export_hash` VARCHAR(64) NOT NULL DEFAULT '',
  `form_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `mis_signature` LONGTEXT DEFAULT NULL,
  `aa_signature` LONGTEXT DEFAULT NULL,
  `sent_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_rsc_group_stage` (`research_group_id`, `research_stage`),
  KEY `idx_rsc_status` (`status`),
  KEY `idx_rsc_adviser` (`adviser_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `crad_research_clearance_notifications` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_key` VARCHAR(190) NOT NULL,
  `recipient_user_id` INT UNSIGNED DEFAULT NULL,
  `recipient_role` VARCHAR(40) NOT NULL DEFAULT '',
  `recipient_email` VARCHAR(190) NOT NULL DEFAULT '',
  `clearance_id` INT UNSIGNED DEFAULT NULL,
  `type` VARCHAR(40) NOT NULL DEFAULT '',
  `title` VARCHAR(190) NOT NULL DEFAULT '',
  `body` TEXT DEFAULT NULL,
  `url` VARCHAR(255) NOT NULL DEFAULT '',
  `is_read` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_rsc_notif_event` (`event_key`),
  KEY `idx_rsc_notif_recipient` (`recipient_user_id`, `recipient_role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `crad_research_clearance_payments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `research_group_id` INT UNSIGNED NOT NULL,
  `research_stage` VARCHAR(20) NOT NULL DEFAULT 'research_1',
  `student_user_id` INT UNSIGNED DEFAULT NULL,
  `uploaded_file` VARCHAR(255) NOT NULL DEFAULT '',
  `uploaded_original` VARCHAR(255) NOT NULL DEFAULT '',
  `or_number` VARCHAR(80) NOT NULL DEFAULT '',
  `remarks` VARCHAR(120) NOT NULL DEFAULT '',
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `approved_by_user_id` INT UNSIGNED DEFAULT NULL,
  `approved_by_name` VARCHAR(160) NOT NULL DEFAULT '',
  `approved_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_rcp_group_stage` (`research_group_id`, `research_stage`),
  KEY `idx_rcp_group` (`research_group_id`),
  KEY `idx_rcp_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
