-- Missing grant final-output tables (runtime ensure was UPDATE-before-CREATE).
-- Safe to re-run: IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS `crad_grant_final_output_submissions` (
    `id`                      INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `grant_application_id`    INT UNSIGNED NOT NULL,
    `version_number`          INT UNSIGNED NOT NULL DEFAULT 1,
    `final_research_title`    VARCHAR(500) NOT NULL DEFAULT '',
    `authors`                 VARCHAR(500) NOT NULL DEFAULT '',
    `abstract`                TEXT NULL,
    `publication_type`        ENUM('Journal','Conference','Book Chapter','Repository','Other') NOT NULL DEFAULT 'Journal',
    `journal_conference`      VARCHAR(255) NOT NULL DEFAULT '',
    `doi`                     VARCHAR(120) NOT NULL DEFAULT '',
    `publication_url`         VARCHAR(500) NOT NULL DEFAULT '',
    `ip_information`          TEXT NULL,
    `copyright_info`          TEXT NULL,
    `patent_info`             TEXT NULL,
    `other_ip_info`           TEXT NULL,
    `final_pdf_path`          VARCHAR(255) NULL DEFAULT NULL,
    `final_pdf_original`      VARCHAR(255) NULL DEFAULT NULL,
    `supporting_files_json`   TEXT NULL,
    `status`                  ENUM('FINAL_OUTPUT_SUBMITTED','RETURNED_FOR_CORRECTION','OUTPUT_VERIFIED') NOT NULL DEFAULT 'FINAL_OUTPUT_SUBMITTED',
    `return_reason`           TEXT NULL,
    `verification_notes`      TEXT NULL,
    `submitted_by_user_id`    INT UNSIGNED NULL DEFAULT NULL,
    `submitted_by_name`       VARCHAR(120) NULL DEFAULT NULL,
    `submitted_at`            DATETIME NULL DEFAULT NULL,
    `reviewed_by_user_id`     INT UNSIGNED NULL DEFAULT NULL,
    `reviewed_by_name`        VARCHAR(120) NULL DEFAULT NULL,
    `reviewed_at`             DATETIME NULL DEFAULT NULL,
    `created_at`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_gfos_application` (`grant_application_id`),
    KEY `idx_gfos_status` (`status`),
    KEY `idx_gfos_submitted` (`submitted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `crad_grant_publications_ip_repository` (
    `id`                      INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `grant_application_id`    INT UNSIGNED NOT NULL,
    `submission_id`           INT UNSIGNED NOT NULL,
    `repository_reference`    VARCHAR(40) NOT NULL DEFAULT '',
    `final_research_title`    VARCHAR(500) NOT NULL DEFAULT '',
    `authors`                 VARCHAR(500) NOT NULL DEFAULT '',
    `abstract`                TEXT NULL,
    `publication_type`        VARCHAR(60) NOT NULL DEFAULT '',
    `journal_conference`      VARCHAR(255) NOT NULL DEFAULT '',
    `doi`                     VARCHAR(120) NOT NULL DEFAULT '',
    `publication_url`         VARCHAR(500) NOT NULL DEFAULT '',
    `ip_information`          TEXT NULL,
    `copyright_info`          TEXT NULL,
    `patent_info`             TEXT NULL,
    `other_ip_info`           TEXT NULL,
    `final_pdf_path`          VARCHAR(255) NULL DEFAULT NULL,
    `final_pdf_original`      VARCHAR(255) NULL DEFAULT NULL,
    `supporting_files_json`   TEXT NULL,
    `verified_by_user_id`     INT UNSIGNED NULL DEFAULT NULL,
    `verified_by_name`        VARCHAR(120) NULL DEFAULT NULL,
    `verified_at`             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_at`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_gpip_application` (`grant_application_id`),
    KEY `idx_gpip_reference` (`repository_reference`),
    KEY `idx_gpip_verified` (`verified_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
